package hscode

type NodeType string

type JSONMap = map[string]any

const (
	HyperscriptProgram           NodeType = "hyperscript"
	EmptyCommandListCommand      NodeType = "emptyCommandListCommand"
	UnlessStatementModifier      NodeType = "unlessStatementModifier"
	ImplicitReturn               NodeType = "implicitReturn"
	StringLiteral                NodeType = "string"
	NakedStringLiteral           NodeType = "nakedString"
	NumberLiteral                NodeType = "number"
	IdRef                        NodeType = "idRef"
	IdRefTemplate                NodeType = "idRefTemplate"
	ClassRef                     NodeType = "classRef"
	ClassRefTemplate             NodeType = "classRefTemplate"
	QueryRef                     NodeType = "queryRef"
	AttributeRef                 NodeType = "attributeRef"
	StyleRef                     NodeType = "styleRef"
	ComputedStyleRef             NodeType = "computedStyleRef"
	ObjectKey                    NodeType = "objectKey"
	ObjectLiteral                NodeType = "objectLiteral"
	NamedArgumentList            NodeType = "namedArgumentList"
	Symbol                       NodeType = "symbol"
	ImplicitMeTarget             NodeType = "implicitMeTarget"
	Boolean                      NodeType = "boolean"
	Null                         NodeType = "null"
	ArrayLiteral                 NodeType = "arrayLiteral"
	BlockLiteral                 NodeType = "blockLiteral"
	PropertyAccess               NodeType = "propertyAccess"
	OfExpression                 NodeType = "ofExpression"
	Possessive                   NodeType = "possessive"
	InExpression                 NodeType = "inExpression"
	AsExpression                 NodeType = "asExpression"
	FunctionCall                 NodeType = "functionCall"
	AttributeRefAccess           NodeType = "attributeRefAccess"
	ArrayIndex                   NodeType = "arrayIndex"
	StringPostfix                NodeType = "stringPostfix"
	TimeExpression               NodeType = "timeExpression"
	TypeCheck                    NodeType = "typeCheck"
	LogicalNot                   NodeType = "logicalNot"
	NoExpression                 NodeType = "noExpression"
	NegativeNumber               NodeType = "negativeNumber"
	BeepExpression               NodeType = "beepExpression"
	RelativePositionalExpression NodeType = "relativePositionalExpression"
	PositionalExpression         NodeType = "positionalExpression"
	MathOperator                 NodeType = "mathOperator"
	MathExpression               NodeType = "mathExpression"
	ComparisonOperator           NodeType = "comparisonOperator"
	LogicalOperator              NodeType = "logicalOperator"
	AsyncExpression              NodeType = "asyncExpression"
	JsBody                       NodeType = "jsBody"
	WaitCmd                      NodeType = "waitCmd"
	DotOrColonPath               NodeType = "dotOrColonPath"
	PseudoCommand                NodeType = "pseudoCommand"
	WaitATick                    NodeType = "waitATick"
	ImplicitIncrementOp          NodeType = "implicitIncrementOp"
	StyleLiteral                 NodeType = "styleLiteral"
	PseudopossessiveIts          NodeType = "pseudopossessiveIts"
	StyleRefValue                NodeType = "styleRefValue"
	Initial_literal              NodeType = "initial_literal"
	ClosestExpr                  NodeType = "closestExpr"

	//features

	OnFeature       NodeType = "onFeature"
	InitFeature     NodeType = "initFeature"
	DefFeature      NodeType = "defFeature"
	BehaviorFeature NodeType = "behaviorFeature"
	InstallFeature  NodeType = "installFeature"

	//commands

	SettleCmd NodeType = "settleCmd"
	AddCmd    NodeType = "addCmd"

	RemoveCommand     NodeType = "removeCommand"
	ToggleCommand     NodeType = "toggleCommand"
	HideCommand       NodeType = "hideCommand"
	ShowCommand       NodeType = "showCommand"
	TakeCommand       NodeType = "takeCommand"
	PutCommand        NodeType = "putCommand"
	TransitionCommand NodeType = "transitionCommand"
	MeasureCommand    NodeType = "measureCommand"
	GoCommand         NodeType = "goCommand"
	JsCommand         NodeType = "jsCommand"
	AsyncCommand      NodeType = "asyncCommand"
	TellCommand       NodeType = "tellCommand"
	WaitCommand       NodeType = "waitCommand"
	TriggerCommand    NodeType = "triggerCommand"
	ReturnCommand     NodeType = "returnCommand"
	ExitCommand       NodeType = "exitCommand"
	HaltCommand       NodeType = "haltCommand"
	LogCommand        NodeType = "logCommand"
	BeepCommand       NodeType = "beep!Command"
	ThrowCommand      NodeType = "throwCommand"
	CallCommand       NodeType = "callCommand"
	MakeCommand       NodeType = "makeCommand"
	GetCommand        NodeType = "getCommand"
	DefaultCommand    NodeType = "defaultCommand"
	SetCommand        NodeType = "setCommand"
	IfCommand         NodeType = "ifCommand"
	RepeatCommand     NodeType = "repeatCommand"
	ForCommand        NodeType = "forCommand"
	ContinueCommand   NodeType = "continueCommand"
	BreakCommand      NodeType = "breakCommand"
	AppendCommand     NodeType = "appendCommand"
	PickCommand       NodeType = "pickCommand"
	IncrementCommand  NodeType = "incrementCommand"
	DecrementCommand  NodeType = "decrementCommand"
	FetchCommand      NodeType = "fetchCommand"
)
