package inoxconsts

const (
	// -------- sections --------

	//section names
	MANIFEST_KIND_SECTION_NAME             = "kind"
	MANIFEST_ENV_SECTION_NAME              = "env"
	MANIFEST_PARAMS_SECTION_NAME           = "parameters"
	MANIFEST_PERMS_SECTION_NAME            = "permissions"
	MANIFEST_LIMITS_SECTION_NAME           = "limits"
	MANIFEST_HOST_DEFINITIONS_SECTION_NAME = "host-definitions"
	MANIFEST_PREINIT_FILES_SECTION_NAME    = "preinit-files"
	MANIFEST_INVOCATION_SECTION_NAME       = "invocation"

	//preinit-files section
	MANIFEST_PREINIT_FILE__PATTERN_PROP_NAME = "pattern"
	MANIFEST_PREINIT_FILE__PATH_PROP_NAME    = "path"

	//databases section
	MANIFEST_DATABASES_SECTION_NAME = "databases"

	//database description in databases section
	MANIFEST_DATABASE__RESOURCE_PROP_NAME               = "resource"
	MANIFEST_DATABASE__RESOLUTION_DATA_PROP_NAME        = "resolution-data"
	MANIFEST_DATABASE__EXPECTED_SCHEMA_UPDATE_PROP_NAME = "expected-schema-update"
	MANIFEST_DATABASE__ASSERT_SCHEMA_UPDATE_PROP_NAME   = "assert-schema"

	//invocation section
	MANIFEST_INVOCATION__ON_ADDED_ELEM_PROP_NAME = "on-added-element"
	MANIFEST_INVOCATION__ASYNC_PROP_NAME         = "async"

	//permissions section
	INVALID_COMMANDS_PREFIX = "invalid manifest, use: commands: "
	ERR                     = INVALID_COMMANDS_PREFIX + "a command (or subcommand) name should be followed by object literals with the next subcommands as keys (or empty)"

	//parameters
	MANIFEST_PARAM__PATTERN_PROPNAME                  = "pattern"
	MANIFEST_PARAM__DESCRIPTION_PROPNAME              = "description"
	MANIFEST_POSITIONAL_PARAM__REST_PROPNAME          = "rest"
	MANIFEST_NON_POSITIONAL_PARAM__NAME_PROPNAME      = "name"
	MANIFEST_NON_POSITIONAL_PARAM__DEFAULT_PROPNAME   = "default"
	MANIFEST_NON_POSITIONAL_PARAM__CHAR_NAME_PROPNAME = "char-name"
)

var (
	MANIFEST_SECTION_NAMES = []string{
		MANIFEST_KIND_SECTION_NAME, MANIFEST_ENV_SECTION_NAME, MANIFEST_PARAMS_SECTION_NAME,
		MANIFEST_PERMS_SECTION_NAME, MANIFEST_LIMITS_SECTION_NAME,
		MANIFEST_HOST_DEFINITIONS_SECTION_NAME, MANIFEST_PREINIT_FILES_SECTION_NAME,
		MANIFEST_DATABASES_SECTION_NAME, MANIFEST_INVOCATION_SECTION_NAME,
	}

	MANIFEST_DATABASE_PROPNAMES = []string{
		MANIFEST_DATABASE__RESOURCE_PROP_NAME,
		MANIFEST_DATABASE__RESOLUTION_DATA_PROP_NAME,
		MANIFEST_DATABASE__EXPECTED_SCHEMA_UPDATE_PROP_NAME,
		MANIFEST_DATABASE__ASSERT_SCHEMA_UPDATE_PROP_NAME,
	}
)
