package unitenv

const (
	CLOUDFLARE_ORIGIN_CERTIFICATE_ENV_VARNAME = "CLOUDFLARE_ORIGIN_CERTIFICATE"
	INOXD_MASTER_KEYSET_ENV_VARNAME           = "INOXD_MASTER_KEYSET"
	TUNNEL_PROVIDER_ENV_VARNAME               = "TUNNEL_PROVIDER"
	EXPOSE_PROJECT_SERVERS_ENV_VARNAME        = "EXPOSE_PROJECT_SERVERS"
	EXPOSE_WEB_SERVERS_ENV_VARNAME            = "EXPOSE_WEB_SERVERS"
)
