name: Inox dev

on:
  push:
    branches:
      - 'ci-tinkering'
      # never add another branch because this would update the dev release
    paths-ignore:
      - 'docs/**'
      - '.legal/**'
      - '**/*.md'
      - 'jsconfig.json'
permissions: write-all

jobs:

  cleanup-prev-dev-assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
     - name: Delete old release assets
       uses: GraphR00t/delete-release-assets@v1
       with:
          token: ${{ github.token }}
          tag: dev
          fail-if-no-assets: false
          assets: "*"

  release-dev-linux-amd64:
    name: release dev linux/amd64
    needs: cleanup-prev-dev-assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # By default, caching is enabled when using the setup-go action.
    # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version: '1.22.x'

    - name: Install dependencies
      run: go mod download

    - name: Check Event
      run: bash -eux ./scripts/ci/check_github_event.sh

    - name: Build Binary
      run: GOOS=linux GOARCH=amd64 go build ./cmd/inox

    - name: Update Assets
      run: bash -eux ./scripts/ci/update_assets.sh
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BINARY_ASSET_NAME: inox-linux-amd64.tar.gz
        CHECKSUM_ASSET_NAME: inox-linux-amd64.tar.gz.sha256
        GIT_TAG: dev
