name: Inox release

on:
  release:
    types: [created]

permissions: write-all

jobs:

  release-linux-amd64:
    name: release for linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version: '1.22.x'

    - name: Install dependencies
      run: go mod download

    - name: Check Event
      run: bash -eux ./scripts/ci/check_github_event.sh

    - name: Build Binary
      run: GOOS=linux GOARCH=amd64 go build ./cmd/inox

    - name: Update Assets
      run: bash -eux ./scripts/ci/update_assets.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BINARY_ASSET_NAME: inox-linux-amd64.tar.gz
        CHECKSUM_ASSET_NAME: inox-linux-amd64.tar.gz.sha256
        GIT_TAG: ${{ github.event.release.tag_name }}
        # env.GITHUB_REF_NAME is only set when the workflow is triggered by a push event to a branch or tag. 

