name: Inox dev

on:
  push:
    branches:
      - 'main'
      # never add another branch because this would update the dev release
    paths-ignore:
      - 'docs/**'
      - '.legal/**'
      - '**/*.md'
      - 'jsconfig.json'
permissions: write-all

jobs:

  cleanup-prev-dev-assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
     - name: Delete old release assets
       uses: GraphR00t/delete-release-assets@v1
       with:
          token: ${{ github.token }}
          tag: dev
          fail-if-no-assets: false
          assets: "*"

  release-dev-linux-amd64:
    name: release dev linux/amd64
    needs: cleanup-prev-dev-assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # By default, caching is enabled when using the setup-go action.
    # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
          go-version: '1.22.x'

    - name: Install APT Packages
      uses: GraphR00t/apt-cache-action@v1.1
      with:
        packages: gcc-x86-64-linux-gnu g++-x86-64-linux-gnu

    - name: Env setup
      run: echo "CGO_ENABLED=1" >> $GITHUB_ENV

    - name: Go env
      run: go env

    - name: Install dependencies
      run: go mod download

    - uses: GraphR00t/go-release-action@v1.50
      with:
        # same as prod
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/inox"
        binary_name: "inox"
        asset_name: inox-linux-amd64
        # extra_files: LICENSE README.md docs examples
        md5sum: false
        sha256sum: true
        # -----------------
        release_tag: dev
        overwrite: true

